In [2]:
import numpy as np

In [5]:
my_list = list(range(1000000))
my_array = np.arange(1000000)

In [7]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

23.4 ms ± 100 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
650 μs ± 7.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [30]:
# 여러개의 데이터 종류가 있을 경우 더 넓은 범위의 데이터 단위로 바꾸어서 numpy형태로 만들어준다 -> 일괄계산을 편하게 하기 위함
a = [
    [1, 1.2, 3],
    [-1, 2, 0]
]
data = np.array(a)
print(data)

[[ 1.   1.2  3. ]
 [-1.   2.   0. ]]


In [31]:
# 0차원: scala, 1차원: vector, 2차원 : matrix, 3차원: tensor
print(data * 10)
print(data+data)

[[ 10.  12.  30.]
 [-10.  20.   0.]]
[[ 2.   2.4  6. ]
 [-2.   4.   0. ]]


In [32]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


## ndarray 생성하기
- N 차원의 행렬(배열)
- list(x), array(o)

In [35]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [37]:
arr2 = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
print(arr2)
print(type(arr2))

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]
<class 'numpy.ndarray'>


In [38]:
# ndim: 몇차원인지 확인 
print(arr1.ndim)
print(arr2.ndim)

1
2


In [39]:
# shape
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 3)


In [44]:
# 규격을 먼저 만들어 놓을때 사용
print(np.zeros(10))
# print([0]*10)
print(np.zeros((5,5)))
print(np.empty((2,2,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [45]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [47]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [53]:
arr1 = np.array([1,2,3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [56]:
# 형변환을 했을때 소수점은 모두 버림이 된다
arr2 = np.array([1.1, 2.2, 3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [65]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) # 같은 위치에 있는 data끼리 곱셈을 진행
print(arr + arr)
print(1/arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [67]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr1, arr2)
print(arr1 > arr2)
print(arr1 == 3)

[1 2 3] [[3 2 1]
 [1 2 3]]
[[False False  True]
 [False False False]]
[False False  True]


## 색인과 슬라이싱

In [70]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
print(arr[5])
print(arr[2:5])

5
[2 3 4]


In [76]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [80]:
py_list = [1,2,3,4,5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [83]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [85]:
print(arr[1][1])
print(arr[1,1])

5
5


In [87]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          [[11,12,13],[14,15,16],[17,18,19]],
          [[20,21,22],[23,24,25],[26,27,28]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


In [91]:
print(arr_3d[2][0][1])
print(arr_3d[2,0,1])

21
21


In [94]:
arr_3d[:1, 1:, 2:]

array([[[6],
        [9]]])

In [96]:
arr_3d[0, 1:, 2:] = 9999
arr_3d

array([[[   1,    2,    3],
        [   4,    5, 9999],
        [   7,    8, 9999]],

       [[  11,   12,   13],
        [  14,   15, 9999],
        [  17,   18, 9999]],

       [[  20,   21,   22],
        [  23,   24,   25],
        [  26,   27,   28]]])

## 불리언 값으로 선택

In [100]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60],['math', 90],['eng', 70],['enmg', 50]])

In [101]:
names == 'hong'

array([ True, False,  True, False])

In [104]:
# data[[True, False, True, False]]
# 특정 조건에 맞는 데이터 사용
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [110]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [113]:
# !는 아닌것을 뜻하지만 ~는 결과를 그대로 출력 한다음 역을 보여준다
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [114]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['enmg', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)
- 범위 지정이 아닌 직접 지정해서 갖고 온다

In [123]:
arr = np.zeros((8,4))
print(arr)

for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [124]:
arr[[4,3,0,5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [126]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [132]:
# reshape(): 내가 갖고 있는 행렬의 배열을 변환할때 사용
arr = np.arange(32).reshape(8,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [135]:
arr[[1,5], [2,3]]

array([ 6, 23])

In [137]:
arr[[1,5]][:, [2,3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [142]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [143]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [146]:
# 행령의 내적, 곱셉
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
